module.exports = {
    Experience : require('./experience'),
    Certification : require('./certification'),
    Skill : require('./skill'),
    Project : require('./project'),
    User : require("./user"),
    ROLES : require("./ROLES"),
    app_status : require("./app_status"),
    Education : require("./education"),
    Cv : require("./cv"),
    PfeBook : require("./pfe_book"),
    OffreStage : require("./offre_stage"),
    OffreApplication : require("./offer_application"),
    StageTask : require("./stage_tasks"),
    TaskStatus : require("./taskStatus"),
}